### ISSUE TITLE
Suggestion: Sapling quest

### ISSUE THREAD

**Issue by b12arr0** [remplerus/skyselection#3]
With the infinite water and lava source blocks in the treasures island, people are going to fill that single chest very quickly.  We need a way to get saplings for wood/planks/chests, please.   I've looked at all recipes and do not see a route to saplings.

**Comment by remplerus** [comment]
You get saplings when reaching infinite void source. I have made some quests for it, just need to push the Update (and make a jei category, but it's harder than i thought) Btw, you can make stone chests as a "workaround"

**Comment by b12arr0** [comment]
So, I've made it to infinite void source.  Based on the infinite water and infinite lava source block methods, I assumed I used the endstone bowl on the infinite void source but it's not giving me anyting.  Am I doing it right?

**Comment by remplerus** [comment]
hm, i thought i have tested it, but somehow my script hasn't saved. pushing a new version today.

**Comment by b12arr0** [comment]
Looks like it's giving me a half full endstone_bowl when I click it on the void cobble block, and then second click is giving me items.   It never reaches full.

**Comment by remplerus** [comment]
yep, i noticed it. but closed. made an update, use version 0.0.4.

**Comment by b12arr0** [comment]
Sounds good! Thanks!
